language: python

addons:
  sonarcloud:
    organization: "aimerfan"
    token:
      secure: $SC_TOKEN
install:
  - pip install django
  - pip install coverage

script:
  - coverage run --source = '.' manage.py test --settings=settings_test
  - coverage xml
  - sonar-scanner -Dsonar.login=$SC_TOKEN
